### ISSUE TITLE
Content Security Policy blocked 

### ISSUE THREAD

**Issue by szefik1987** [aspnet/jquery-ajax-unobtrusive#23]
jquery-ajax-unobtrusive is blocked by CSP in line:
**return Function.constructor.apply(null, argNames);**
"Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'"."

In according to this site https://developer.mozilla.org/en-US/docs/Archive/B2G_OS/Firefox_OS_apps/Building_apps_for_Firefox_OS/CSP
The function constructor is banned

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @szefik1987. One of our team members will look into it and get back to you.

**Comment by mkArtakMSFT** [comment]
@javiercn, can you please look into this and see what other options can be applied here?

**Comment by javiercn** [comment]
We can't do anything here. Essentially what the code is doing is building a function on the fly (a form of eval) that is being disallowed by CSP.
That form of eval is required for supporting writing expressions in the ajax related data-ajax-* attributes like data-ajax-begin, for example:
```html
<form ... data-ajax-complete="$(this).hide()">
...
</form>
```

The alternative would require to either deprecate allowing expressions on the attributes or doing significant re-engineering to build all these expressions before-hand and emit proper functions for them on a script tag at the end of the page, which would likely, also have to be attributed with a nonce to bypass csp validation.

**Comment by mkArtakMSFT** [comment]
Closing this as the amount of work required to fix this is not worth the effort.

**Comment by KarsonAlford** [comment]
**Explanation:**
The getFunction method first tries to find the function in the DOM and falls back to eval via Function.constructor.  Currently if one of the handlers (OnBegin, OnSuccess, etc.) is not defined then null is passed into getFunction which is not a function and therefore is evaluated and a function created that returns null. 


**Possible Fix:**

    function getFunction(code, argNames) {
        if (!code) return function() { return null; }



**Current Options:**
Option 1) Add a NOOP function for all the handlers that you are not using.

`window.noop = function() { return null; }`

OnBegin="noop"
OnSuccess="noop"


Option 2) Replace Function.apply so that the eval is not possible.  Inspired by [this blog post](https://statuscode.ch/2017/03/CSP-unsafe-eval-and-jquery).

    Function.apply = function (element, args) {
        if (args && args.length && args.length !== 0) {
            var code = args[args.length - 1];
            if (code) {
                console.log('JavaScript evaluation prevented - ' + code);
            }
        }
        return function () { return null; };
    };

**Comment by Guy171** [comment]
I experienced that issue and found a way to resolve it https://jquerys.space/questions/the-object-formdata-cannot-be-instantiated-as-a-constructor
