### ISSUE TITLE
Have this package available on CDNJS

### ISSUE THREAD

**Issue by Eilon** [aspnet/jquery-ajax-unobtrusive#30]
See https://github.com/aspnet/jquery-validation-unobtrusive/issues/76 for info.

**Comment by Eilon** [comment]
Tagging @DamianEdwards @jbagga FYI

**Comment by jbagga** [comment]
Yes the decision was to have this package on NuGet and Microsoft Ajax CDN only cc @Eilon

**Comment by Eilon** [comment]
That's right, closing.

**Comment by TheJuki** [comment]
[Library Manager](https://github.com/aspnet/LibraryManager) currently only uses CDNJS and file system.

**Comment by bchavez** [comment]
Please reopen this issue and add the AJAX unobtrusive to CDNJS.

![devenv_2170](https://user-images.githubusercontent.com/478118/45897832-095e1800-bd8d-11e8-960e-e0a0d7d0a994.png)

Generally, Microsoft developer tools and products should match up.

Thanks,
Brian

:beach_umbrella: :trumpet: **[Beach Boys - Good Vibrations (Nick Warren bootleg)](https://www.youtube.com/watch?v=PZiV-Sd2uOs)**

**Comment by Eilon** [comment]
@mkArtakMSFT please have a look.

**Comment by AdamWillden** [comment]
Can you please do this soon as currently I have no means of using a VS client package manager (be it LibMan or NPM) to get a local copy without manually downloading the file.

I was using NPM only to find you've decided not to publish there (which I think is crazy). I needed the latest version so that `formnovalidate` is respected.

Following on from this request for CDNJS you should also be aware that the unpkg option [does pull from NPM](https://unpkg.com/). So, if publishing to CDNJS is going to take a while to sort, please just publish one more version to NPM so I can use LibMan consistently in the mean time.

I just went to check if LibMan had any plans to support aspnet CDN only to find this where someone is having the exact same issue as me (in regards to this repo): https://github.com/aspnet/LibraryManager/issues/67#issuecomment-423721101

**Comment by javiercn** [comment]
@Eilon @mkArtakMSFT This is on PR in the cdnjs repo
https://github.com/cdnjs/cdnjs/pull/13029

**Comment by felipepessoto** [comment]
@javiercn the reviewer requested some changes

**Comment by mkArtakMSFT** [comment]
@javiercn, please update your PR as requested by the re viewers.

**Comment by javiercn** [comment]
This was done
