### ISSUE TITLE
Property data-ajax-cache is not resolved right

### ISSUE THREAD

**Issue by spudcz** [aspnet/jquery-ajax-unobtrusive#5]
line 94
**cache: !!element.getAttribute("data-ajax-cache")**

When I have anchor defined like this:
&lt;a href="..." data-ajax="true" data-ajax-cache="false"&gt;...&lt;/a&gt; 
then the javascript code above sets cache to true.

element.getAttribute("data-ajax-cache") returns string "false"
!element.getAttribute("data-ajax-cache") returns boolean false
!!element.getAttribute("data-ajax-cache") returns boolean true

Consider changing line 94 to this:
**cache: (element.getAttribute("data-ajax-cache") || "").toLowerCase() === "true"**

**Comment by Eilon** [comment]
@ajaybhargavb can you do a fix based on inspiration from the PR at https://github.com/aspnet/jquery-ajax-unobtrusive/pull/6? We primarily want to support only the *strings* `true` and `false` (but in either case). Not concerned about someone setting an actual Boolean in the DOM (because that makes no sense).

**Comment by ajaybhargavb** [comment]
afaffa66dfa9fb4198175d2e6663c764dc488128 and 44bd91ee383ff86339965c1958e6c59102fa8b74
